name: .NET Build & Test Project

on:
  workflow_call:
    inputs:
      project-path:
        description: 'Path to the project to build'
        required: true
        type: string

      artifact-name:
        description: 'Name of the artifact to upload'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - uses: dotnet/nbgv@v0.4
      id: nbgv

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project-path }}

    - name: Build Debug
      run: dotnet build -c debug --no-restore ${{ inputs.project-path }}

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "GitHubActions;report-warnings=true" ${{ inputs.project-path }}

    - name: .NET Build Release & Pack
      run: dotnet build -c release -o "publish" ${{ inputs.project-path }}
        
    - name: Upload .NET build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: "publish"
      